[[redirects]]
    from = "/interactive-comments-section"
    to = "https://geodask-interactive-comments-section.netlify.app"
    status = 200

[[redirects]]
    from = "/"
    to = "/404.html"
    force = true
    status = 404
