[[redirects]]
    from = "/interactive-comments-section/*"
    to = "https://geodask-ics.netlify.app/"
    status = 200
[[headers]]
    for = "/*"
    [headers.values]
        Access-Control-Allow-Origin = "*"
